#!/usr/bin/env python3
"""
Wrap MIR-generated SPIR-V function as a proper Vulkan compute shader.
"""

import sys
import re


def extract_circuit_ops(spirv_asm):
    """Extract just the circuit operations from MIR-generated SPIR-V."""
    lines = spirv_asm.split("\n")

    ops = []
    in_function = False
    for line in lines:
        if "OpLabel" in line:
            in_function = True
            continue
        if "OpReturn" in line or "OpFunctionEnd" in line:
            break
        if in_function and line.strip() and not line.strip().startswith(";"):
            # Skip input initialization
            if "input" in line.lower() and "OpCopyObject" in line:
                continue
            ops.append(line)

    return ops


def generate_compute_shader_spirv(circuit_ops, num_inputs=8, num_outputs=8):
    """Generate complete compute shader with buffer I/O."""

    lines = []
    id_counter = 1

    def next_id():
        nonlocal id_counter
        result = id_counter
        id_counter += 1
        return f"%{result}"

    # Remap all IDs in circuit_ops to avoid conflicts
    id_mapping = {}

    # Header
    lines.append("; SPIR-V Vulkan Compute Shader")
    lines.append("; Generated by VeryLogo for tower field S-box")
    lines.append("; Version: 1.3")
    lines.append("; Generator: VeryLogo")
    lines.append("; Bound: 500")
    lines.append("; Schema: 0")
    lines.append("")
    lines.append("OpCapability Shader")
    lines.append("OpMemoryModel Logical GLSL450")

    main_id = next_id()
    gid_var_id = next_id()
    in_buf_id = next_id()
    out_buf_id = next_id()

    lines.append(f'OpEntryPoint GLCompute {main_id} "main" {gid_var_id}')
    lines.append(f"OpExecutionMode {main_id} LocalSize 64 1 1")
    lines.append("")

    # Decorations
    lines.append(f"OpDecorate {gid_var_id} BuiltIn GlobalInvocationId")

    arr_id = next_id()
    in_struct_id = next_id()
    out_struct_id = next_id()

    lines.append(f"OpDecorate {arr_id} ArrayStride 4")
    lines.append(f"OpMemberDecorate {in_struct_id} 0 Offset 0")
    lines.append(f"OpDecorate {in_struct_id} BufferBlock")
    lines.append(f"OpDecorate {in_buf_id} DescriptorSet 0")
    lines.append(f"OpDecorate {in_buf_id} Binding 0")
    lines.append(f"OpMemberDecorate {out_struct_id} 0 Offset 0")
    lines.append(f"OpDecorate {out_struct_id} BufferBlock")
    lines.append(f"OpDecorate {out_buf_id} DescriptorSet 0")
    lines.append(f"OpDecorate {out_buf_id} Binding 1")
    lines.append("")

    # Types
    void_id = next_id()
    uint_id = next_id()
    int_id = next_id()
    v3uint_id = next_id()
    ptr_in_v3uint = next_id()
    ptr_unif_uint = next_id()
    ptr_unif_in_struct = next_id()
    ptr_unif_out_struct = next_id()
    func_type_id = next_id()

    lines.append(f"{void_id} = OpTypeVoid")
    lines.append(f"{uint_id} = OpTypeInt 32 0")
    lines.append(f"{int_id} = OpTypeInt 32 1")
    lines.append(f"{v3uint_id} = OpTypeVector {uint_id} 3")
    lines.append(f"{ptr_in_v3uint} = OpTypePointer Input {v3uint_id}")
    lines.append(f"{ptr_unif_uint} = OpTypePointer Uniform {uint_id}")
    lines.append(f"{arr_id} = OpTypeRuntimeArray {uint_id}")
    lines.append(f"{in_struct_id} = OpTypeStruct {arr_id}")
    lines.append(f"{out_struct_id} = OpTypeStruct {arr_id}")
    lines.append(f"{ptr_unif_in_struct} = OpTypePointer Uniform {in_struct_id}")
    lines.append(f"{ptr_unif_out_struct} = OpTypePointer Uniform {out_struct_id}")
    lines.append(f"{func_type_id} = OpTypeFunction {void_id}")
    lines.append("")

    # Constants
    const_0 = next_id()
    const_8 = next_id()
    int_const_0 = next_id()
    const_ffff = next_id()

    lines.append(f"{const_0} = OpConstant {uint_id} 0")
    lines.append(f"{const_8} = OpConstant {uint_id} 8")
    lines.append(f"{int_const_0} = OpConstant {int_id} 0")
    lines.append(f"{const_ffff} = OpConstant {uint_id} 4294967295")

    const_ids = {i: next_id() for i in range(1, num_inputs)}
    for i, cid in const_ids.items():
        lines.append(f"{cid} = OpConstant {uint_id} {i}")
    lines.append("")

    # Variables
    lines.append(f"{gid_var_id} = OpVariable {ptr_in_v3uint} Input")
    lines.append(f"{in_buf_id} = OpVariable {ptr_unif_in_struct} Uniform")
    lines.append(f"{out_buf_id} = OpVariable {ptr_unif_out_struct} Uniform")
    lines.append("")

    # Main function
    lines.append(f"{main_id} = OpFunction {void_id} None {func_type_id}")
    entry_label = next_id()
    lines.append(f"{entry_label} = OpLabel")
    lines.append("")

    # Get thread ID
    gid_loaded = next_id()
    tid_id = next_id()
    lines.append(f"{gid_loaded} = OpLoad {v3uint_id} {gid_var_id}")
    lines.append(f"{tid_id} = OpCompositeExtract {uint_id} {gid_loaded} 0")

    # Base offset = tid * 8
    base_offset_id = next_id()
    lines.append(f"{base_offset_id} = OpIMul {uint_id} {tid_id} {const_8}")
    lines.append("")

    # Load inputs
    input_val_ids = []
    for i in range(num_inputs):
        offset_id = next_id()
        ptr_id = next_id()
        val_id = next_id()

        if i == 0:
            lines.append(f"{offset_id} = OpIAdd {uint_id} {base_offset_id} {const_0}")
        else:
            lines.append(
                f"{offset_id} = OpIAdd {uint_id} {base_offset_id} {const_ids[i]}"
            )

        lines.append(
            f"{ptr_id} = OpAccessChain {ptr_unif_uint} {in_buf_id} {int_const_0} {offset_id}"
        )
        lines.append(f"{val_id} = OpLoad {uint_id} {ptr_id}")
        input_val_ids.append(val_id)
        id_mapping[f"%{12 + i}"] = val_id  # Map MIR input IDs

    lines.append("")
    lines.append("; Circuit operations")

    # Process circuit ops and remap IDs
    for op in circuit_ops:
        # Remap any %XX references
        new_op = op
        for old_id, new_id in id_mapping.items():
            new_op = re.sub(rf"\b{re.escape(old_id)}\b", new_id, new_op)

        # Assign new ID for result if this defines one
        match = re.match(r"^(%\d+)\s*=", op)
        if match:
            old_result_id = match.group(1)
            new_result_id = next_id()
            id_mapping[old_result_id] = new_result_id
            new_op = re.sub(
                rf"^{re.escape(old_result_id)}\s*=", f"{new_result_id} =", new_op
            )
            # Also remap in the operation
            for old_id, new_id in id_mapping.items():
                if old_id != old_result_id:
                    new_op = re.sub(rf"\b{re.escape(old_id)}\b", new_id, new_op)
            # Replace type ID
            new_op = re.sub(r"%1\b", uint_id, new_op)

        lines.append(new_op)

    lines.append("")

    # Store outputs - need to find output IDs from MIR
    # For now, assume last 8 computed values are outputs
    # This is a simplification - should parse from MIR output_regs
    lines.append("; Store outputs")
    print("Warning: Output mapping not yet implemented - using placeholder")

    lines.append("")
    lines.append("OpReturn")
    lines.append("OpFunctionEnd")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: wrap_spirv_compute.py input.spvasm output.spvasm")
        return 1

    input_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "out/wrapped.spvasm"

    with open(input_path, "r") as f:
        spirv_asm = f.read()

    circuit_ops = extract_circuit_ops(spirv_asm)
    print(f"Extracted {len(circuit_ops)} circuit operations")

    compute_shader = generate_compute_shader_spirv(circuit_ops)

    with open(output_path, "w") as f:
        f.write(compute_shader)

    print(f"Written compute shader to: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
